name: 'Bump Version Action'
description: 'Bump version in setup.py or pyproject.toml, commit, tag, and create PR'
inputs:
  bump_type:
    description: 'Version bump type (major, minor, patch)'
    required: true
    default: 'patch'
  github_token:
    description: 'GitHub token for committing and creating PR'
    required: true
  base_branch:
    description: 'Base branch for the PR'
    required: false
    default: 'main'
  labels:
    description: 'Labels to add to the PR'
    required: false
outputs:
  current_version:
    description: 'The version before bumping'
    value: ${{ steps.bump.outputs.current_version }}
  new_version:
    description: 'The new version after bumping'
    value: ${{ steps.bump.outputs.new_version }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.bump_type }}
    - ${{ inputs.github_token }}
    - ${{ inputs.base_branch }}
    - ${{ inputs.labels }}
